# Generated by Django 3.1.7 on 2021-04-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210415_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='value',
            field=models.ImageField(default='avatar.jpg', upload_to='blog/photos'),
        ),
    ]
