# Generated by Django 3.1.7 on 2021-04-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210419_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='intro',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='value',
            field=models.ImageField(default='avatar.jpg', upload_to='photos/%Y%m%d'),
        ),
    ]
