# Generated by Django 3.1.7 on 2021-04-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210419_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
