# Generated by Django 3.1.7 on 2021-04-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
