# Generated by Django 3.1.7 on 2021-04-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20210423_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='value',
            field=models.ImageField(default='avatar.jpg', unique=True, upload_to='photos/%Y%m%d'),
        ),
    ]
