# Generated by Django 3.1.7 on 2021-04-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20210424_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='value',
            field=models.ImageField(upload_to='photos/%Y%m%d'),
        ),
    ]
