# Generated by Django 3.1.7 on 2021-04-25 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20210425_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='like_persons',
            field=models.ManyToManyField(blank=True, related_name='like_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
