# Generated by Django 3.1.7 on 2021-04-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20210426_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='read_count',
        ),
    ]
