# Generated by Django 3.1.7 on 2021-04-21 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_auto_20210420_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ancestor',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply_user',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_comments', to='comment.comment'),
        ),
    ]
