# Generated by Django 3.1.7 on 2021-04-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_auto_20210421_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='quote_comment_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
