# Generated by Django 3.1.7 on 2021-04-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_remove_comment_quote_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='quote_comment_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
